from config.constants import AVG_SIZES


HIDDEN_DIM = 10
CRITIC_BATCH_SIZE = 50
ACTOR_BATCH_SIZE = 70
NB_STEPS = 50
CRITIC_LR = 5e-8
ACTOR_LR = 1e-2

LB_INIT = AVG_SIZES * -5
UB_INIT = AVG_SIZES* 5

LB_FINAL = LB_INIT
UB_FINAL = UB_INIT
NB_SHORT_ROLLOUTS= 100
SHORT_HORIZON = 100
LONG_HORIZON = 10000

