from config.constants import AVG_SIZES


HIDDEN_DIM = 12
CRITIC_BATCH_SIZE = 70
ACTOR_BATCH_SIZE = 50
NB_STEPS = 500
CRITIC_LR = 5e-8
ACTOR_LR = 1e-2

LB_INIT = AVG_SIZES * -3
UB_INIT = AVG_SIZES* 3

LB_FINAL = AVG_SIZES *-5
UB_FINAL = AVG_SIZES *5
NB_SHORT_ROLLOUTS= 100
SHORT_HORIZON = 100
LONG_HORIZON = 10000

